### PR TITLE
Add markdown and images for Java blog part 1

### PR DESCRIPTION
**Pull request by paquel**
Created a new Blog Post to comment on the VSPK-Java library

### CODE REVIEW

**Comment by pdellaert** [comment]
Hi @paquel,

Haven't read the whole blog yet, but thanks for the contribution: 
couple of first remarks:
- can you put the date on the 17th (so we don't overload with blog posts on the same day)
- can you add some tags
- Your images of the VSD contain the name of a customer... this is not something we want
- The images of code, should be added as code, not as images... You can do this using:
```
{% highlight java %}
CODE
{% endhighlight %}
```

**Comment by pdellaert** [comment]
Rest looks super good/cool!! Thanks :)

**Comment by paquel** [comment]
Hi @pdellaert .  Thanks for the feedback.  I'll try to make the changes today.

**Comment by paquel** [comment]
Hi @pdellaert .  Please review today's changes.  Thank you.

**Comment by paquel** [comment]
Oops.   Architect slides still wrong.

**Comment by paquel** [comment]
Now ready for review.

**Comment by pdellaert** [comment]
Thanks, i'll delete the remaining Gem files and .project file, no worries :)

**Pull request merged**
