### PR TITLE
New posts

### PR DESCRIPTION
**Pull request by jonasvermeulen**
Added post on TCP Stateful Firewalling

### CODE REVIEW

**Comment by jonasvermeulen** [comment]
Any feedback / update ?

**Comment by t00f** [comment]
Looks good to me. Waiting for @bvandewalle for his reading :)

**Comment by bvandewalle** [comment]
I have been discussing this by email with Jonas and he might want to resubmit :-)

**Comment by jonasvermeulen** [comment]
Resubmitted with changes squashed

**Comment by t00f** [comment]
@bvandewalle do you confirm ?

**Comment by bvandewalle** [comment]
Thanks for the content

**Pull request merged**
