### PR TITLE
Post on running docker containers within Nuage tenant networks

### PR DESCRIPTION
**Pull request by jonasvermeulen**
Post that was shared with EMEA Open Community.
We would like this to be posted online as well.
It contains 1 page - with some code examples. Need some guidance on how to markup code changes.

### CODE REVIEW

**Comment by dttocs** [comment]
Thanks Jonas,

We will review and once Bernard has approved we can post this.

**Comment by jonasvermeulen** [comment]
any update ?

**Comment by primalmotion** [comment]
Hi, I can't really test right now, but could send me a picture of the article running on a web browser?I just want to see how it looks.

Thanks,

**Comment by bvandewalle** [comment]
Hi jonas.

Regarding the content it's very good.
I have a couple change to suggest and will do it in a couple days when I
get some more connectivity.

Thanks,
Bernard

**Comment by jonasvermeulen** [comment]
Hi Antoine, I have just used an online MD editor (eg http://dillinger.io/)
to prepare the content.

**Pull request merged**
